MySQLServer: ''
MySQLPort: 3306
MySQLDatabase: ''
MySQLUsername: ''
MySQLPassword: ''
MySQLOption: '?allowPublicKeyRetrieval=true&useSSL=false'

DiscordWebHook: ''
Area: ''
AdminUUID: ''

ProxyCheckIoAPI: ''

isAntiProxy: false
isAntiVPN: false
AntiThroughList: []

DiscordInviteURL: 'https://discord.gg/Xx8AfZXSP6'